- hosts: localhost
  remote_user: root

  tasks:
  - name: Stopping a VM on Azure
    command: /usr/bin/az vm stop --resource-group "test" --name {{ vm_name }}

  - name: Delete the VM from Azure
    command: /usr/bin/az vm delete --resource-group "test" --name {{ vm_name }}
