---
# add hosts to inventory during an ansible run 'ansible-playbook add_hosts.yml -e "host_file=/tmp/hosts"'

- name: add hosts
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: True
  roles:
    - add_hosts

- hosts: "{{ vm_name }}"
  remote_user: root
  no_log: True
  roles:
  - sat6reg
