---
# tasks file for plex_install
- name: fail playbook if plex.rpm is undefined
  fail:
    msg: "plexrpm variable is undefined"
  when: plexrpm is undefined

- import_tasks: rhel_reg.yml
- import_tasks: sysconfig.yml

- name: installing plexmedia server rpm
  yum:
    name: "{{ plexrpm }}"
    state: present

- name: enabling and starting plex service
  service:
    name: plexmediaserver.service
    state: started
    enabled: yes

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    owner: plex
    group: plex
  with_items:
    - /plex_media
    - /plex_media/tv_shows
    - /plex_media/movies
    - /plex_media/misc

- name: setup cron to enforce plex ownership
  cron:
    minute: 0
    hour: "*/4"
    user: root
    job: "/usr/bin/chown plex:plex -R /plex_media/"
