---
# registering the server with Red Hat and update VM

- name: remove old content host name
  file:
    state: absent
    path: /etc/rhsm/facts/katello.facts

- name: registering system w/ subscription manager
  redhat_subscription:
    state: present
    org_id: "{{ org_id }}"
    activationkey: "{{ activationkey }}"

- name: enabling Red Hat repos
  command: /usr/sbin/subscription-manager repos --disable="*" --enable=rhel-7-server-rpms
  ignore_errors: True

- name: update server
  yum:
    name: "*"
    state: latest
