---
# tasks file for plex_maint

- name: Prevent run without tags
  fail: msg="You must run this playbook with tags!"

- import_tasks: plex_chmod.yml
  tags: chmod

- import_tasks: plex_rsync.yml
  tags: rsync

- import_tasks: plex_update.yml
  tags: update
