---
- name: check for backup directory
  stat:
    path: "{{ myvol }}"
  register: plex_vol

- name: "rsync: check and make sure plex backup volume is mounted"
  fail:
    msg: "{{ myvol }} does not exist"
  when: plex_vol.stat.isdir is not defined

- name: "rsync: volume is presented"
  synchronize:
    src: "{{ src }}"
    dest: "{{ dest }}"
    archive: yes
    delete: yes
  delegate_to: "{{ inventory_hostname }}"
  when: plex_vol.stat.isdir is defined
