---
#- name: check for backup directory
#  stat:
#    path: "{{ myvol }}"
#  register: plex_vol

- name: "rsync: check and make sure plex backup volume is mounted"
  fail:
    msg: "{{ myvol }} does not exist"
  with_items: ansible_mounts
  when: item.mount != '/backup'

- name: "rsync: volume is presented"
  synchronize:
    src: "{{ src }}"
    dest: "{{ dest }}"
    archive: yes
    delete: yes
  delegate_to: "{{ inventory_hostname }}"
  when: item.mount == '/backup'
