---
# tasks file for plex-maint

- name: "rsync: check and make sure plex backup volume is mounted"
  fail:
    msg: "{{ myvol }} does not exist"
  when: myvol is not exists

- name: "rsync: volume is presented"
  synchronize:
    src: "{{ src }}"
    dest: "{{ dest }}"
    archive: yes
    delete: yes
  when: myvol is mount
