---
#- name: check for backup directory
#  stat:
#    path: "{{ myvol }}"
#  register: plex_vol

- name: check for backup directory
  command: mountpoint -q {{ myvol }}
  register: volume_stat
  failed_when: False
  changed_when: False

- name: "rsync: check and make sure plex backup volume is mounted"
  fail:
    msg: "{{ myvol }} does not exist"
  when: volume_stat.rc != 0

- name: "rsync: volume is presented"
  synchronize:
    src: "{{ src }}"
    dest: "{{ dest }}"
    archive: yes
    delete: yes
  delegate_to: "{{ inventory_hostname }}"
  when: volume_stat.rc == 0
