---
# handlers file for sat6reg
- name: enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - goferd
    - chronyd
#    - puppet

- name: reboot host
  shell: sleep 10 && /sbin/shutdown -r now
  async: 300
  poll: 0
  become: true
