---
# defaults file for var_test
#company: "US Dog Insurance"
#location: Richmond
#env: Development
#os_vers: 7.5
#is_virt: "TRUE"
UD0005ABLY:
  name: 'UD0005ABLY'
  location: 'Blythewood'
  company: 'US Life Insurance'
  domain: 'GENWORTH'
  os_vers: '7.5'
  env: 'Development'
  is_virtual: "TRUE"

UD0210ALYN:
  name: 'UD0210ALYN'
  location: 'Lynchburg'
  company: 'US Life Insurance'
  domain: 'DMZ'
  os_vers: '7.5'
  env: 'Development'
  is_virtual: 'TRUE'

UP0014ALLI:
  name: 'UP0014ALLI'
  location: 'Lynchburg'
  company: 'US Life Insurance'
  domain: 'GENWORTH'
  os_vers: '7.5'
  env: 'Production'
  is_virtual: 'TRUE'
