---
# tasks file for plex_rsync

- name: check and make sure plex backup volume is mounted
  fail:
    msg: "{{ myvol }} must be a mount point"
  when: myvol is not is_mount

- name: volume is presented
  synchronize:
    src: "{{ src }}"
    dest: "{{ dest }}"
    archive: yes
    delete: yes
  when: myvol is is_mount
