---
# tasks file for azure_deploy
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: test
    name: "{{ vm_name }}"
    vm_size: Standard_DS1_v2
    admin_username: demouser
    admin_password: Redhat123456
    network_interfaces: test-vnet
    os_type: Windows
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2019-Datacenter
      version: latest
