---
# tasks file for var_test
- name: Checking for company variable
  set_fact:
    company_1: "USLI"
  when: UD0005ABLY.company == "US Life Insurance"

- name: checking for location variable
  set_fact:
    location_1: "BLY"
  when: UD0005ABLY.location == "Blythewood"

- name: checking for environment variable
  set_fact:
    env_1: "DEV"
  when: UD0005ABLY.env == "Development"

- name: checking for OS 7 version
  set_fact:
    os_vers1: "7"
  when: UD0005ABLY.os_vers >= 7.0

- name: checking for OS 6 version
  set_fact:
    os_vers1: "6"
  when: UD0005ABLY.os_vers < 7.0

- name: checking to see if this is a virtual machine
  set_fact:
    is_virt_1: "VM"
  when: UD0005ABLY.is_virtual == "TRUE"

- name: checking to see if this is a physical machine
  set_fact:
    is_virt_1: "Physical"
  when: UD0005ABLY.is_virtual == "FALSE"

- name: stitch them together
  set_fact:
    final_var: "{{ company_1 }}-{{ location_1 }}-{{ env_1 }}-RHELv{{ os_vers1 }}-{{ is_virt_1 }}"

- name: output environment variable
  debug:
    msg: "{{ final_var }}"
